name: Trivy Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Uncomment and configure this step if your project utilizes multi-stage builds or platform-specific builds
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build . -t product-manager

      - name: Run Trivy Scan
        run: |
          docker run --rm -v $(pwd):/workdir aquasec/trivy:latest image -f json -o trivy_results.json product-manager

      - name: Upload Trivy Results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: trivy_results.json
